import{S as P,a as h,i as s}from"./assets/vendor-BXU5-F4Y.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();const q=new P(".gallery a",{captionsData:"alt",captionDelay:400}),f=document.querySelector(".loader"),u=document.querySelector(".gallery"),d=document.querySelector(".load-more-btn");function p(){f.classList.remove("ishidden")}function m(){f.classList.add("ishidden")}function g(r){const t=r.map(({webformatURL:c,largeImageURL:i,tags:e,likes:o,views:a,comments:S,downloads:E})=>`<li class="gallery-item">
                <a class="gallery-link" href="${i}">
                    <img class="gallery-image" src="${c}" alt="${e}" />
                    <div class="info">
                        <p><b>Likes:</b> ${o}</p>
                        <p><b>Views:</b> ${a}</p>
                        <p><b>Comments:</b> ${S}</p>
                        <p><b>Downloads:</b> ${E}</p>
                    </div>
                </a>
            </li>`).join("");u.insertAdjacentHTML("beforeend",t),q.refresh()}function R(){u.innerHTML=""}function y(){d.classList.remove("ishidden")}function b(){d.classList.add("ishidden")}const M="53036317-ecc3b65bfc32e98f0ebbd349e";h.defaults.baseURL="https://pixabay.com/api/";async function L(r,t){return await h("",{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}}).then(({data:i})=>i)}const v=document.querySelector(".form");v.addEventListener("submit",$);d.addEventListener("click",O);let n=1,l="",w=0;async function $(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),l===""){s.error({position:"topRight",message:"Please enter a search query!"});return}b(),R(),p(),n=1;try{const t=await L(l,n);if(t.hits.length===0)return s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});g(t.hits),t.totalHits>15?(y(),w=Math.ceil(t.totalHits/15)):s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),v.reset()}catch(t){s.error({message:t.message,position:"topRight"})}finally{m()}}async function O(){n+=1,p(),b();try{const r=await L(l,n);if(r.hits.length===0)return s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});g(r.hits);const t=u.firstElementChild.getBoundingClientRect().height;x(t),w===n?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):y()}catch(r){s.error({message:r.message,position:"topRight"})}finally{m()}}function x(r){window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
