import{S as P,a as f,i as a}from"./assets/vendor-BXU5-F4Y.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const q=new P(".gallery a",{captionsData:"alt",captionDelay:400}),h=document.querySelector(".loader"),d=document.querySelector(".gallery"),u=document.querySelector(".load-more-btn");function m(){h.classList.remove("ishidden")}function p(){h.classList.add("ishidden")}function g(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:n,comments:w,downloads:S})=>`<li class="gallery-item">
                <a class="gallery-link" href="${s}">
                    <img class="gallery-image" src="${i}" alt="${e}" />
                    <div class="info">
                        <p><b>Likes:</b> ${r}</p>
                        <p><b>Views:</b> ${n}</p>
                        <p><b>Comments:</b> ${w}</p>
                        <p><b>Downloads:</b> ${S}</p>
                    </div>
                </a>
            </li>`).join("");d.insertAdjacentHTML("beforeend",t),q.refresh()}function R(){d.innerHTML=""}function M(){u.classList.remove("ishidden")}function y(){u.classList.add("ishidden")}const $="53036317-ecc3b65bfc32e98f0ebbd349e";f.defaults.baseURL="https://pixabay.com/api/";async function b(o,t){return await f("",{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}}).then(({data:s})=>s)}const L=document.querySelector(".form");L.addEventListener("submit",B);u.addEventListener("click",O);let c=1,l="",E=0;async function B(o){if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),l===""){a.error({position:"topRight",message:"Please enter a search query!"});return}y(),R(),m(),c=1;try{const t=await b(l,c);if(t.hits.length===0)return a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});g(t.hits);const i=d.firstElementChild.getBoundingClientRect().height;v(i),t.totalHits>15&&(M(),E=Math.ceil(t.totalHits/15)),L.reset()}catch(t){a.error({message:t.message,position:"topRight"})}finally{p()}}async function O(){c+=1,m();try{const o=await b(l,c);E===c&&(y(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),g(o.hits);const t=d.firstElementChild.getBoundingClientRect().height;v(t)}catch(o){a.error({message:o.message,position:"topRight"})}finally{p()}}function v(o){window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
