import{S as P,a as f,i as a}from"./assets/vendor-BXU5-F4Y.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();let q=new P(".gallery a");const h=document.querySelector(".loader"),c=document.querySelector(".gallery"),u=document.querySelector(".load-more-btn");function m(){h.classList.remove("ishidden")}function p(){h.classList.add("ishidden")}function g(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:n,comments:w,downloads:S})=>`<li class="gallery-item">
                <a class="gallery-link" href="${s}">
                    <img class="gallery-image" src="${i}" alt="${e}" />
                    <div class="info">
                        <p><b>Likes:</b> ${o}</p>
                        <p><b>Views:</b> ${n}</p>
                        <p><b>Comments:</b> ${w}</p>
                        <p><b>Downloads:</b> ${S}</p>
                    </div>
                </a>
            </li>`).join("");c.insertAdjacentHTML("beforeend",t),q.refresh()}function R(){c.innerHTML=""}function M(){u.classList.remove("ishidden")}function y(){u.classList.add("ishidden")}const $="53036317-ecc3b65bfc32e98f0ebbd349e";f.defaults.baseURL="https://pixabay.com/api/";async function b(r,t){return await f("",{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}}).then(({data:s})=>s)}const L=document.querySelector(".form");L.addEventListener("submit",B);u.addEventListener("click",O);let d=1,l="",E=0;async function B(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),l===""){a.error({position:"topRight",message:"Please enter a search query!"});return}y(),R(),m(),d=1;try{const t=await b(l);if(t.hits.length===0)return a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});g(t.hits);const i=c.firstElementChild.getBoundingClientRect().height;v(i),t.totalHits>15&&(M(),E=Math.ceil(t.totalHits/15)),L.reset()}catch(t){a.error({message:t.message,position:"topRight"})}finally{p()}}async function O(){d+=1,m();try{const r=await b(l);E===d&&(y(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),g(r.hits);const t=c.firstElementChild.getBoundingClientRect().height;v(t)}catch(r){a.error({message:r.message,position:"topRight"})}finally{p()}}function v(r){window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
